name: Continuous-Integration

on:
  push:
    branches:
      - 'main'
      - 'feature/integrateBrowserStack'
  pull_request:
    branches:
      -'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - name: Env Setup
      uses: browserstack/github-actions/setup-env@master
      with:
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean
    - name: Run tests
      run: mvn verify -P suite
    - name: TestNG Report
      uses: actions/upload-artifact@v3
      with:
        path: ./target/surefire-reports

