name: Continuous-Integration

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      -'main'

jobs:
  init:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean
      - name: Run tests
        run: mvn verify
      - uses: actions/upload-artifact@v1
        with:
          name: TestNG Report
          path: ./target/surefire-reports/index.html      

